name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build and Push Docker images
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.push-image.outputs.image }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          # fetch-depth: 0 needed for `git rev-list --count` to work properly
          fetch-depth: 0
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: dhpup/guestbook
          tags: |
            type=sha
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.0'
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.7.0
