name: Release

on:
  release:
    types:
      - published

env:
  GOPRIVATE: "github.com/dhpup"

jobs:
  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.push-image.outputs.image }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          # fetch-depth: 0 needed for `git rev-list --count` to work properly
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PKG_PAT }}
      - 
        name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.0'
      - 
        name: Set Tag
        run: |
          TAG="${GITHUB_REF_NAME:1}"
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "RELEASE_TAG=${TAG}" >> $GITHUB_ENV
      -  
        name: Build and push
        id: push-image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.RELEASE_TAG }}
